### ISSUE TITLE
parser.js:268 throw new Error(str);

### ISSUE THREAD

**Issue by RuggeriLuca** [MarcosEllys/awesome-newman-html-template#38]
hello 
i'm betting the below error can you help me ?

c:\Users\Agent\AppData\Roaming\npm\node_modules\newman-reporter-html\node_modules\handlebars\dist\cjs\handlebars\compiler\parser.js:268
            throw new Error(str);
            ^

Error: Parse error on line 795:
...pan class="pl-c1">{{</span><span class="
-----------------------^
Expecting 'ID', 'STRING', 'NUMBER', 'BOOLEAN', 'UNDEFINED', 'NULL', 'DATA', got 'INVALID'
    at Parser.parseError (c:\Users\Agent\AppData\Roaming\npm\node_modules\newman-reporter-html\node_modules\handlebars\dist\cjs\handlebars\compiler\parser.js:268:19)
    at Parser.parse (c:\Users\Agent\AppData\Roaming\npm\node_modules\newman-reporter-html\node_modules\handlebars\dist\cjs\handlebars\compiler\parser.js:337:30)
    at HandlebarsEnvironment.parse (c:\Users\Agent\AppData\Roaming\npm\node_modules\newman-reporter-html\node_modules\handlebars\dist\cjs\handlebars\compiler\base.js:46:43)
    at compileInput (c:\Users\Agent\AppData\Roaming\npm\node_modules\newman-reporter-html\node_modules\handlebars\dist\cjs\handlebars\compiler\compiler.js:515:19)
    at ret (c:\Users\Agent\AppData\Roaming\npm\node_modules\newman-reporter-html\node_modules\handlebars\dist\cjs\handlebars\compiler\compiler.js:524:18)
    at EventEmitter.<anonymous> (c:\Users\Agent\AppData\Roaming\npm\node_modules\newman-reporter-html\lib\index.js:161:22)
    at EventEmitter.emit (c:\Users\Agent\AppData\Roaming\npm\node_modules\newman\node_modules\eventemitter3\index.js:203:33)
    at done (c:\Users\Agent\AppData\Roaming\npm\node_modules\newman\lib\run\index.js:277:29)
    at c:\Users\Agent\AppData\Roaming\npm\node_modules\newman\node_modules\postman-runtime\lib\backpack\index.js:56:34
    at PostmanCollectionRun._process (c:\Users\Agent\AppData\Roaming\npm\node_modules\newman\node_modules\postman-runtime\lib\runner\run.js:161:13)
    at PostmanCollectionRun.<anonymous> (c:\Users\Agent\AppData\Roaming\npm\node_modules\newman\node_modules\postman-runtime\lib\runner\run.js:166:76)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)

**Comment by MarcosEllys** [comment]
Hello @RuggeriLuca, i sorry for it takes an answer, maybe you change my original template, the error is so clear here

**.pan class="pl-c1">{{<span class="**, could send me a template as example, i don't know how help you without the template

**Comment by cmis** [comment]
Hi @MarcosEllys getting the exact same error on a unmodifyed template.

**Comment by Abhijeet0908** [comment]
Hi @MarcosEllys I'm getting the same error on unmodifyed template that you have provided in the below link.
[https://github.com/MarcosEllys/awesome-newman-html-template]

And you have provided 'newman' command also, what is 'my.collection.postman.json' in this command.
Please find the attached screenshot for the machine environment and error details.
Please let me know, what I'm doing wrong.

![npm](https://user-images.githubusercontent.com/65222274/82069197-9a1b0180-96f0-11ea-89bc-239d6ba67a94.PNG)
