### ISSUE TITLE
Doesn't work for me.

### ISSUE THREAD

**Issue by chibuzorobilom** [MarcosEllys/awesome-newman-html-template#46]
I have the HTML report installed, but when I run 

newman run -e my.environment.json -g my.globals.json --reporters cli,html --reporter-html-template templates/htmlreqres.hbs --reporter-html-export my_report.html my.collection.postman.json

I get:

newman: could not load "html" reporter
  this seems to be a problem in the "html" reporter.

Error: ENOENT: no such file or directory, open 'templates/htmlreqres.hbs'

Error: ENOENT: no such file or directory, open 'templates/htmlreqres.hbs'
    at Object.openSync (node:fs:497:3)
    at Object.readFileSync (node:fs:393:35)
    at new PostmanHTMLReporter (/usr/local/lib/node_modules/newman-reporter-html/lib/index.js:59:42)
    at /usr/local/lib/node_modules/newman/lib/run/index.js:389:68
    at arrayEach (/usr/local/lib/node_modules/newman/node_modules/lodash/lodash.js:516:11)
    at Function.forEach (/usr/local/lib/node_modules/newman/node_modules/lodash/lodash.js:9368:14)
    at /usr/local/lib/node_modules/newman/lib/run/index.js:346:39
    at /usr/local/lib/node_modules/newman/node_modules/postman-runtime/lib/backpack/index.js:58:34
    at /usr/local/lib/node_modules/newman/node_modules/postman-runtime/lib/runner/index.js:113:20
    at extractRunnableItems (/usr/local/lib/node_modules/newman/node_modules/postman-runtime/lib/runner/extract-runnable-items.js:273:35)
    at PostmanCollectionRunner.run (/usr/local/lib/node_modules/newman/node_modules/postman-runtime/lib/runner/index.js:96:9)
    at /usr/local/lib/node_modules/newman/lib/run/index.js:160:16
    at /usr/local/lib/node_modules/newman/lib/run/options.js:394:9
    at wrapper (/usr/local/lib/node_modules/newman/node_modules/async/dist/async.js:268:20)
    at /usr/local/lib/node_modules/newman/node_modules/async/dist/async.js:2753:19
    at wrapper (/usr/local/lib/node_modules/newman/node_modules/async/dist/async.js:268:20) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: 'templates/htmlreqres.hbs'
}
newman

**Comment by MarcosEllys** [comment]
Sorry, i can't reproduce this case.
